### ISSUE TITLE
Multiple users created by resourceServer example on each login

### ISSUE THREAD

**Issue by Type1J** [prime-8-consulting/meteor-oauth2#1]
When signing out and then signing back in on resourceServer, the user collection has a new document on resourceServer for each time that the user signs in.

The new document has the same email under profile.name as the previous document that was created for the same (resourceOwner) user.

If the remote (resourceOwner) user is used to sign in on multiple machines, a similar problem occurs.

**Comment by Type1J** [comment]
[I believe that the problem is here](https://github.com/prime-8-consulting/meteor-oauth2/blob/1c56e1ac73d86ee134c9df7423c5ca2acc95ee06/packages/meteor-oauth2-client/meteor_server.js#L27). This id is used to [search the "users" collection for an existing user](https://github.com/meteor/meteor/blob/0f98ea22fcc3f10cfd36aba66e531bf22c70f96e/packages/accounts-base/accounts_server.js#L1334). It cannot be random. I believe that it should be unique to a resourceOwner server.

**Comment by vangorra** [comment]
Agreed. This should not be random, rather it should be the id returned by the getIdentity() call.

**Comment by Type1J** [comment]
Thanks!

**Comment by vangorra** [comment]
I'm glad there has been some feedback, especially for a bug.
