### ISSUE TITLE
accounts-ui button.login-buttons is overloaded

### ISSUE THREAD

**Issue by awatson1978** [prime-8-consulting/meteor-oauth2#16]
Our trusty login-button is overloaded, and doing double-duty linking to the ClientApplication OAuth configuration page and the signIn dropdown menu.

![screen shot 2016-03-10 at 3 34 06 pm](https://cloud.githubusercontent.com/assets/675910/13688268/8eafab22-e6d5-11e5-888d-c30905e7b98e.png)

The various stakeholders I'm working with are going to want to specify [their own sign-in and sign-up pages](https://github.com/clinical-meteor/active-entry), and probably even their own OAuth Configuration Page.  

Given our own devices, we would begin by removing `accounts-ui` and replacing with `clinical:accounts-entry`.  Or at least `useraccounts:core`.  Not sure if either of those are the direction you're wanting to take this repository; but that's the direction I and my clients are interested in heading.  Are interests aligned in this regard?

**Comment by vangorra** [comment]
The login buttons and their behavior is generated by meteor's login-buttons blaze template. We get very little control over what they say or how they behave. If you happen to install the client package and use the buttons template, then you are presented with the use case presented in the clientApplication.

There is however, nothing preventing a developer from creating their own login templates and linking to the resourceServer's authenticate route.

I think the presence of accounts-ui in the clientApplication example provides the dev with a quick and concise workflow of how the process works. Using a 3rd party package adds additional unknowns in how the process is truly operating.
