### ISSUE TITLE
Should A6, and A7 be in the clientApplication instead of resourceServer?

### ISSUE THREAD

**Issue by awatson1978** [prime-8-consulting/meteor-oauth2#17]
So, I was walking through the OAuth flow, and taking a 'higher-level' look, now that the initial documentation is reconciled.  Everything seemed to be going great, up through step A5.1 where we Generate Access Tokens.  

![screen shot 2016-03-10 at 4 02 02 pm](https://cloud.githubusercontent.com/assets/675910/13688863/74cce824-e6d9-11e5-92a7-b85ecd35ad77.png)

But A6 and A7 I'm not entirely convinced about. I feel like they should maybe be in the ClientApplication instead of the ResourceServer, right?  Like... they're in the wrong window above.  I expect the pop-up window to be where I sign-in and authorize apps/access; and then things bounce back to the original window, where the tokens will be accessing resources and they'll be integrated into the app.  Right?

**Comment by vangorra** [comment]
You raise a valid point. A6 and A7 make more sense in the clientApplication. It would be relatively simple to add that to client/index.html of the clientApplication.
