### ISSUE TITLE
Unable to base64 decode state from OAuth query: undefined

### ISSUE THREAD

**Issue by awatson1978** [prime-8-consulting/meteor-oauth2#18]
Hi there!
Have you ever seen an error like this?  The OAuth handshake doesn't seem to be working.  This is a highly customized fork, so it's most likely me having just broken things.  But I thought I'd ask in case you knew what it was.  Otherwise, I can close.  
Thanks!

``` js
I20160322-11:44:52.208(-7)? query {}
W20160322-11:44:52.033(-7) (oauth.js:79) Unable to base64 decode state from OAuth query: undefined
W20160322-11:44:52.035(-7) (oauth.js:79) Unable to base64 decode state from OAuth query: undefined
W20160322-11:44:52.037(-7) (oauth.js:406) Error in OAuth Server: Failed to complete OAuth handshake

failed [500] OAuth2Error: Invalid code     at OAuth2Error (/Users/abigailwatson/Code/Galaxy/hl7-argonaut-fhir/examples/resourceServer/.meteor/local/isopacks/prime8consulting_meteor-oauth2-server/npm/node_modules/oauth2-server/lib/error.js:30:12)     at /Users/abigailwatson/Code/Galaxy/hl7-argonaut-fhir/examples/resourceServer/.meteor/local/isopacks/prime8consulting_meteor-oauth2-server/npm/node_modules/oauth2-server/lib/grant.js:195:19     at MeteorModel.<anonymous> (packages/prime8consulting:meteor-oauth2-s...
```

**Comment by awatson1978** [comment]
Nevermind.  This was my mistake.  Making progress as I audit the flow and flush the bug out.  Things coming along nicely.  Thank you again for putting together these oauth packages.

**Comment by adamgins** [comment]
Hi @awatson1978 I am trying to write a Oauth connecter for IBM Connections... I can get the OAuth request back, but they don't support "state"....


 From their documentation: " IBM Connections Cloud does not support the state parameter, so the application should store the state in the user’s session. "

See https://forums.meteor.com/t/oauth-flow-without-state/18861/5

Any ideas pls?
