### ISSUE TITLE
oauth implementation with custom ui

### ISSUE THREAD

**Issue by lawrencehui** [prime-8-consulting/meteor-oauth2#19]
Hi I'm just trying out the package and follow through the examples (both client and server). I came to the point when I can successfully obtain the authCode and be able to console.log the result (inside oAuth2Server.callMethod.authCodeGrant). 

Since I would like to implement the closing of the pop-up browser and extract the authCode in my client side Meteor.loginWithMeteorOAuth2Server callback, can you advice how I can do this? 

Thanks!.

**Comment by vangorra** [comment]
In step A5.2 of the example, click the link. The window will close automatically and the authorization code will be returned to the client application.
