### ISSUE TITLE
Is it possible to use client and server in the same Meteor Application?

### ISSUE THREAD

**Issue by leonnardo** [prime-8-consulting/meteor-oauth2#22]
@vangorra I tried to use like examples and it worked fine, but in my case I need to login with accounts-password without using an external oauth, is there a way?

Thanks!

**Comment by vangorra** [comment]
You can use either package independently of the other. Technically, there are 3 unique ways to set this up.
1. Combined - Your site uses both meteor-oauth2-client and meteor-oauth2-server. The client is used to oauth2 authenticate against another meteor server. Also, your server provides oauth2 based authentication.
2. Client only - Your site will be performing oauth2 authentication against another meteor server. Possible in addition to using accounts-password.
3. Server only - Your site uses something like account-password for your users but also provides 3rd party sites to authenticated against your server using oauth2.

Does this clear things up?
