### ISSUE TITLE
Could not get client collection from client side.

### ISSUE THREAD

**Issue by oychao** [prime-8-consulting/meteor-oauth2#24]
I've noticed that the client collection is only available from server side (But why?).
So how do I do if I want to list all clients from client side?

**Comment by oychao** [comment]
I used Meteor.methods({...}) and Meteor.call('...') to retrieve client collection data from server, but I still don't understand why client collection data shouldn't be available from client side. Really hope someone could tell me, many thanks.

**Comment by Kostanos** [comment]
Hi @CharlesOy it is by security, if you publish clients collection, you'll dispose all clients to each other.

What I did in my case (in admin page, where I can add/remove/edit clients):

server publisher:

```
import {oAuth2Server} from 'meteor/prime8consulting:meteor-oauth2-server';
import {Roles} from 'meteor/alanning:roles';

// We publish all oauth2 clients only for admin
Meteor.publish('OAuth2Clients', function(){
  if (!this.userId) {
    return this.ready();
  };
  if (!Roles.userIsInRole(this.userId, ['admin'])){
    return this.ready();
  };
  return oAuth2Server.collections.client.find();
});
```

And you'll need to subscribe in client to this publication, but only in case if currently logged in user is admin.

Hope it helps.

**Comment by oychao** [comment]
@Kostanos Thank you.

I know the collection shall not be available from the client of `meteor/prime8consulting:meteor-oauth2-server`. I mean I cannot get the collection from the client side of Meteor.
I have the same code like yours in my project, but when I subscribe in client, I got an `undefined` error.

Here is my **server code**:

``` javascript
import {oAuth2Server} from 'meteor/prime8consulting:meteor-oauth2-server';
import {Roles} from 'meteor/alanning:roles';
import * as CONS from '../../lib/constants';
import * as METHODS from '../../lib/methods'

...

  Meteor.publish(METHODS.PUBLISH_OAUTH2_LIST, function () {
    if (Roles.userIsInRole(this.userId, [CONS.SUPERUSER], Roles.GLOBAL_GROUP)) {
      return oAuth2Server.collections.client.find({});
    } else {
      return this.ready();
    }
  });

...
```

and **client code**:

``` javascript
import {oAuth2Server} from 'meteor/prime8consulting:meteor-oauth2-server';
import * as METHODS from '../../../../lib/methods';

...

  Meteor.subscribe(METHODS.PUBLISH_OAUTH2_LIST);
  let list = oAuth2Server.collections.client.find({}).fetch() // ERROR

...

```

and **error message** in browser console:

```
Exception from Tracker recompute function:
meteor.js?hash=ae8b8af…:930 TypeError: Cannot read property 'find' of undefined
    at OauthManager.getMeteorData (Manager.jsx:36)
    at ReactMeteorData.jsx:89
    ...
```

Am I doing anything wrong anywhere? Thank you again.

**Comment by oychao** [comment]
@Kostanos 
Also, I noticed that it seems `oAuth2Server.collections.client` is not exposed to client side.
[meteor-oauth2-server/common.js#L35](https://github.com/prime-8-consulting/meteor-oauth2/blob/master/packages/meteor-oauth2-server/common.js#L35)

And I checked the DDP messages, the server returned an `unsub` message as soon as the client send the `sub` message.

```
["{"msg":"sub","id":"PPaFHRGgscGmjuzkQ","name":"pub.oauth2.list","params":[]}"]
["{"msg":"unsub","id":"PPaFHRGgscGmjuzkQ"}"]
```

**Comment by Kostanos** [comment]
try this on the client:

```
import * as METHODS from '../../../../lib/methods';

...
  var clientCollection = new Mongo.Collection('users'); // you may initialize collection in different place and include here
  // Probably oAuth2Server.collections.client is not exposed to the client
  Meteor.subscribe(METHODS.PUBLISH_OAUTH2_LIST, function(){
      // Use callback on subscribe, to insure you got the data
      let list = clientCollection.find({}).fetch();
  });

...
```


Sorry, I'm currently with different project, and can't get better code for you, let me know if you still have questions.
