### ISSUE TITLE
upgrade meteor to use npm and node-oauth-server to 3.x ?

### ISSUE THREAD

**Issue by crapthings** [prime-8-consulting/meteor-oauth2#26]
trying to upgrade node-oauth-server to 3.x.

its easy to upgrade meteor but failed with oauth-server.

https://github.com/oauthjs/node-oauth2-server/wiki/Migrating-from-2.x-to-3.x

**Comment by vangorra** [comment]
According to the package.js for this project's oauth-server meteor package. The package has a hard dependency on oauth2-server 2.4.1. It's my understanding that oauth2-server 3.x has a drastic api difference. Pull requests are welcome. 

https://github.com/prime-8-consulting/meteor-oauth2/blob/master/packages/meteor-oauth2-server/package.js#L27

**Comment by crapthings** [comment]
yes i'm trying to make it work with 3.x

https://github.com/crapthings/meteor-oauth2/blob/oauth2-server-3/packages/meteor-oauth2-server/server.js#L166

i've changed all api and dependency according to "migration from 2x to 3x"

but part of code still no working.

maybe we can't use mockApp to fake headers.

**Comment by vangorra** [comment]
Perhaps a change to mock app would help. It's hard to say. I looked into
the 3.x branch when originally authoring these packages. It looks like the
mock app isn't necessary anymore as the API has become more reusable.
3.x is still in beta. Further, the aren't any immediate advantages to
updating to the new API as it is more likely to cause compatibility
conflicts.

**Comment by crapthings** [comment]
can we use scope in current implementing?

**Comment by vangorra** [comment]
Could you elaborate? I don't understand the question.
