### ISSUE TITLE
Authorization Code Flow

### ISSUE THREAD

**Issue by awatson1978** [prime-8-consulting/meteor-oauth2#4]
Is the following diagram an accurate representation of the code in this repository?  (As compared to this [OAuth Authentication Flow v1.0a Diagram](http://www.phpbuilder.com/imagesvr_ce/2463/Oauth-image001.png), which I'm not 100% sure is OAuth2 or OAuth1.)  Asking because I'd like to add some documentation to the Readme.

![OAuth 2 Authorization](http://ldapwiki.willeke.com/attach/OAuth%202%20Authorization%20Code%20Flow/oauth2-authorization-code-flow.png)

**Comment by vangorra** [comment]
Yes, this diagram is an accurate representation of the code in the repo.

If you intend to include the diagram, make sure we have the proper licensing for the image. I'm not sure if the copyright on the bottom is enough credit.

**Comment by awatson1978** [comment]
I'm thinking of redoing the diagrams from scratch, so they match the source code.  

Excellent work, by the way!  This is exactly what we've been looking for!  It's a major contribution to the Meteor ecosystem.  Kudos!

**Comment by vangorra** [comment]
The naming convention used for the example of this app seem off. Please chime in on #8 so we can correct this issue.

**Comment by awatson1978** [comment]
Sounds good.  This diagram is probably a little too simplistic anyhow, and the API calls aren't necessarily implemented in the example code.  However, it's providing a lot of great reference material for the detailed diagram I'm putting together.  Keeping the good stuff, and closing.
