### ISSUE TITLE
Web Sequence Diagrams

### ISSUE THREAD

**Issue by awatson1978** [prime-8-consulting/meteor-oauth2#5]
More sequence diagrams for the readme.  Are the following diagrams correct?  
# 
#### OAuth 2.0 in Web API - General Overview

![OAuth 2.0 in Web API](http://codebetter.com/howarddierking/files/2011/10/diagram.png)
# 
#### OAuth 2.0 in Web API - Detailed Example

![OAuth 2.0 in Web API - Detailed Example](http://codebetter.com/howarddierking/files/2011/10/diagram-1.png)

**Comment by vangorra** [comment]
These diagrams are good example of the oauth2 process and would describe the communication well.

**Comment by vangorra** [comment]
Just remember, in meteor, the "Authorization Server" and "Resource Server" are the same application.

The naming convention used for the example of this app seem off. Please chime in on #8 so we can correct this issue.

**Comment by awatson1978** [comment]
After a bunch of review, I think the first webdiagram above may have Client/ResourceOwner reversed.  Closing this one out in preference for the new diagram in #6.
