### ISSUE TITLE
HL7 FHIR Flowchart

### ISSUE THREAD

**Issue by awatson1978** [prime-8-consulting/meteor-oauth2#6]
I and about 5 or 6 clients are trying to implement the [HL7 FHIR spec](http://fhirblog.com/2014/06/18/fhir-oauth2-and-the-mobile-client/), which relies on OAuth2, and are referencing the following diagram:

![FHIR, Oauth2 and the Mobile client](https://fhirblog.files.wordpress.com/2014/06/oauth-mobile.png)

The above diagram differs a bit from the [web sequence diagrams](https://github.com/prime-8-consulting/meteor-oauth2/issues/5) found at [www.websequencediagrams.com](www.websequencediagrams.com) and what's in the source code.  

I'm 95% sure these are all compatible diagrams, but could you confirm where in the above diagram the [resourceOwner](https://github.com/prime-8-consulting/meteor-oauth2/tree/master/examples/resourceOwner) is understood to be?  I'm a little confused as to whether it would be 

a) between the Embedded Browser and Authorization Server
b) a synonym for the Embedded Browser
c) a synonym for the Desktop App/Mobile
d) a synonym for the User
e) the unlabeled lavendar zone

I'm going to update this diagram accordingly for the ClinicalMeteor HL7 FHIR resources; and would like the source code and documentation to all be in alignment.

**Comment by vangorra** [comment]
In this diagram, the "resourceOwner" would be both the "Authentication Server' and "Resource Server". 

Based on your questions, it seems clear that I have named the examples incorrectly.

The naming convention used for the example of this app seem off. Please chime in on #8 so we can correct this issue.

**Comment by awatson1978** [comment]
Okay, first version of the new websequence diagram.  Uses the colors and iconography of the overview graph in #7.  Has the same level of drill-down as the FHIR diagram.  Next step I'd like to do is document the package API calls, like in #4.

![oauth - websequence](https://cloud.githubusercontent.com/assets/675910/13647858/ddd350aa-e5ea-11e5-9366-f778cf66651b.png)

**Comment by vangorra** [comment]
I don't see any errors in this chart. The design is fantastic! I look forward to it getting integrated in the docs.

**Comment by awatson1978** [comment]
Pull Request #10 just submitted with a revised version of the diagram that includes the OAuth Configuration workflow.  I think I'm missing where to add the Redirect URI though.  :-/

![OAuthWebSequenceWithConfig](https://raw.githubusercontent.com/awatson1978/meteor-oauth2/readme-updates/documentation/OAuthWebSequenceWithConfig.png)

**Comment by awatson1978** [comment]
Mostly all implemented by #14.  Good for me to do an initial handoff to coworkers and stakeholders.

**Comment by vangorra** [comment]
Great. Now that this diagram is included in the source readme, will you edit the readme to point to the diagram from this repo's source rather than to your fork?
