### ISSUE TITLE
Naming convention used in docs and examples directory structure is off.

### ISSUE THREAD

**Issue by vangorra** [prime-8-consulting/meteor-oauth2#8]
The naming of the examples of "resourceOwner" and "resourceServer" is terribly confusing and inconsistent with the naming convention used for oauth2 documentation.

As described by many sources, including digital ocean. The naming convention is as follows:

> Resource Owner: User
> 
> The resource owner is the user who authorizes an application to access their account. The application's access to the user's account is limited to the "scope" of the authorization granted (e.g. read or write access).
> 
> Resource / Authorization Server: API
> 
> The resource server hosts the protected user accounts, and the authorization server verifies the identity of the user then issues access tokens to the application.
> 
> From an application developer's point of view, a service's API fulfills both the resource and authorization server roles. We will refer to both of these roles combined, as the Service or API role.
> 
> Client: Application
> 
> The client is the application that wants to access the user's account. Before it may do so, it must be authorized by the user, and the authorization must be validated by the API.

Source: https://www.digitalocean.com/community/tutorials/an-introduction-to-oauth-2

Knowing this, the following name changes should occurs:
examples/resource -> examples/application
examples/resourceOwner -> examples/resourceServer

**Comment by awatson1978** [comment]
Thanks for looking at these diagrams, and considering the possibility that there are some inconsistencies with the naming convention.  

For what it's worth, I'm not saying that any one of these other diagrams is authoritative.  I've run into quite a few different implementations of OAuth over the years; and there's a reason they're implementations, and not clones, forks, instances, etc.  They each tend to differ a bit; so, no judgements here.  Just trying to point out what documentation other people will be looking at, and trying to do a reconciliation.  

I'm doing a deeper dive into the code, drafting some new diagrams that can be customized specifically to the Meteor stack, and thinking through different steps forward.  There's a couple of different ways to skin this cat.  Will get back to you tomorrow.  (I'm on paid time working on this right now, and looking forward to getting this up and running.)

**Comment by awatson1978** [comment]
So, I've read through pretty much the entire package now, and am in agreement:  the examples are basically named backwards to the typical convention.  Doing the following refactor would clarify a lot of things:

examples/resourceOwner -> examples/resourceServer
examples/resourceServer -> examples/clientApplication

Would you like to do this?  Shall I submit a pull request?  There's a number of other refactors that I could also recommend to make the entire codebase clearer.  Would you be willing to consider feature PRs if I kept them small and concise?

**Comment by vangorra** [comment]
The goal of releasing this package was to give back to the community and become more involved. So we are committed to collaborating via pull requests. We are especially interested in new features so long as they fit withing the scope of this package's purpose.

You are already working on better documentation and features. Keep it up. I'll rename the examples and related documentation references.
